### PR TITLE
Update 04-awkward.md

### PR DESCRIPTION
**Pull request by GuillermoFidalgo**
added hint and solution block for awkward quizz

### CODE REVIEW

**Comment by GuillermoFidalgo** [comment]
This PR should close #27

**Review by klieret — APPROVED** [review]
Thanks

**Comment by klieret** [comment]
@GuillermoFidalgo Small tip: If you write "Closes #27" in the description of either the commit or PR, it will automatically close the issue.

Also, don't forget to fill in a commit title ;)

**Comment by GuillermoFidalgo** [comment]
It has to be exactly the phrase?

"Closes #27"
I thought what I wrote did that already.

**Pull request merged**
