### PR TITLE
fix: modernize and correct some parts

### PR DESCRIPTION
**Pull request by henryiii**
Fixes for things that have changed or moved.

### CODE REVIEW

**Comment by henryiii** [comment]
@klieret @eduardo-rodrigues @jpivarski Who maintains the repo? I'll be teaching this in about three hours and have a couple of open PRs.

**Review by jpivarski — APPROVED** [review]
Also good improvements. Ready to merge!

**Comment by eduardo-rodrigues** [comment]
Ah, Jim was speedy 👍 !

**Comment by jpivarski** [comment]
> @klieret @eduardo-rodrigues @jpivarski Who maintains the repo? I'll be teaching this in about three hours and have a couple of open PRs.

I wasn't sure. This is something we should figure out, in general.

**Comment by henryiii** [comment]
No, I don't have merge rights, otherwise I would've just gone ahead and done it. :)

**Comment by henryiii** [comment]
Thanks!

**Pull request merged**
